# Generated by Django 5.2.9 on 2026-02-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('username', models.CharField()),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.talaba')),
            ],
        ),
    ]
