# Generated by Django 5.2.9 on 2026-02-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_botuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='talaba',
        ),
    ]
