# Generated by Django 5.2.9 on 2026-02-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_botuser_talaba'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='Main.botuser'),
        ),
    ]
