# Generated by Django 5.2.9 on 2026-02-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_talaba_bot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
